on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      USE_SSH: true
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: 'Use SSH agent'
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: 'Deploy to GitHub Pages'
        env:
          USE_SSH: true
        working-directory: './Circuits'
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          npm ci
          npm run docusaurus deploy
