name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Circuits/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        working-directory: ./Circuits
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          git config --global user.email "84284151+FunnPunn@users.noreply.github.com"
          git config --global user.name "FunnPunn"
          npm ci
          npm run docusaurus deploy
